
TELEGRAM_BOT_TOKEN = "7642666619:AAH3-MtRPnv4P9jFUnZW5zajArMwuWC-r-g" 
TELEGRAM_CHANNEL_ID = "-1002557612563"  

[users]
lena = "Mohamad12"
user1 = "password123"

[packages]
ffmpeg = true
libsm6 = true
libxext6 = true