
TELEGRAM_BOT_TOKEN = "7642666619:AAH3-MtRPnv4P9jFUnZW5zajArMwuWC-r-g" 
TELEGRAM_CHANNEL_ID = "-1002557612563"  


TELEGRAM_imege_TOKEN = "7642666619:AAH3-MtRPnv4P9jFUnZW5zajArMwuWC-r-g"


# -- تعريف القنوات التي يمكن النشر إليها --
# >> تأكد من أن هذا السطر مكتوب هكذا بالضبط <<
[telegram_channels]

# "اسم سهل" = "معرف القناة أو @username"
"القناة الإخبارية الارشيفية" = "-1002899423747"
"قناة أخبار المشاهير" = "@CelebrityNewsChannel"
"قناة المشاهير" = "-1002000491877"